"""add queued+maintanence

Revision ID: 0b1254aa0d04
Revises: 30273b55ed8a
Create Date: 2025-11-11 13:25:29.137388

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1254aa0d04'
down_revision: Union[str, Sequence[str], None] = '30273b55ed8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('maintenance_start', sa.DateTime(), nullable=True))
    op.add_column('device', sa.Column('maintenance_end', sa.DateTime(), nullable=True))
    op.add_column('reservation', sa.Column('queued', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'queued')
    op.drop_column('device', 'maintenance_end')
    op.drop_column('device', 'maintenance_start')
    # ### end Alembic commands ###
