"""relations

Revision ID: 1869e16c4642
Revises: 3fffb391d766
Create Date: 2025-10-06 17:26:35.137377

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1869e16c4642'
down_revision: Union[str, Sequence[str], None] = '3fffb391d766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_type_id', sa.Integer(), nullable=False))
    op.add_column('device', sa.Column('server_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'device', 'server', ['server_id'], ['id'])
    op.create_foreign_key(None, 'device', 'device_type', ['device_type_id'], ['id'])
    op.add_column('experiment', sa.Column('server_id', sa.Integer(), nullable=False))
    op.add_column('experiment', sa.Column('device_type_id', sa.Integer(), nullable=True))
    op.add_column('experiment', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('experiment', sa.Column('software_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experiment', 'device', ['device_id'], ['id'])
    op.create_foreign_key(None, 'experiment', 'server', ['server_id'], ['id'])
    op.create_foreign_key(None, 'experiment', 'software', ['software_id'], ['id'])
    op.create_foreign_key(None, 'experiment', 'device_type', ['device_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_column('experiment', 'software_id')
    op.drop_column('experiment', 'device_id')
    op.drop_column('experiment', 'device_type_id')
    op.drop_column('experiment', 'server_id')
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'server_id')
    op.drop_column('device', 'device_type_id')
    # ### end Alembic commands ###
