"""cleaner reservation models

Revision ID: 22d6a11c8bae
Revises: 6e60c77d248c
Create Date: 2025-09-29 11:09:28.311430

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d6a11c8bae'
down_revision: Union[str, Sequence[str], None] = '6e60c77d248c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reservation_workspace_id_fkey'), 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('reservation_workspace_id_fkey'), 'reservation', 'workspace', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
