"""reservations fix

Revision ID: 30273b55ed8a
Revises: b7cd7a4f6d0b
Create Date: 2025-10-27 15:56:41.527700

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30273b55ed8a'
down_revision: Union[str, Sequence[str], None] = 'b7cd7a4f6d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reservation', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reservation', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
