"""add option to migration

Revision ID: 492bf9cc6e9b
Revises: 735be5d3c2b1
Create Date: 2025-11-25 10:59:53.056334

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492bf9cc6e9b'
down_revision: Union[str, Sequence[str], None] = '735be5d3c2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('argument_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['argument_id'], ['argument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_name'), 'option', ['name'], unique=True)
    op.create_index(op.f('ix_option_output_value'), 'option', ['output_value'], unique=False)
    op.create_index(op.f('ix_option_value'), 'option', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_value'), table_name='option')
    op.drop_index(op.f('ix_option_output_value'), table_name='option')
    op.drop_index(op.f('ix_option_name'), table_name='option')
    op.drop_table('option')
    # ### end Alembic commands ###
