"""remove queued reservation

Revision ID: 4a9c8f4bd93d
Revises: 492bf9cc6e9b
Create Date: 2025-11-25 21:30:36.164396

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9c8f4bd93d'
down_revision: Union[str, Sequence[str], None] = '492bf9cc6e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'queued')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('queued', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
