"""fix schema to device type relation

Revision ID: 563f965136d5
Revises: 4e4114ec77da
Create Date: 2025-10-07 11:34:06.162043

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563f965136d5'
down_revision: Union[str, Sequence[str], None] = '4e4114ec77da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_type', sa.Column('schema_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'device_type', 'schema', ['schema_id'], ['id'])
    op.drop_constraint(op.f('schema_device_type_id_fkey'), 'schema', type_='foreignkey')
    op.drop_column('schema', 'device_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema', sa.Column('device_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('schema_device_type_id_fkey'), 'schema', 'device_type', ['device_type_id'], ['id'])
    op.drop_constraint(None, 'device_type', type_='foreignkey')
    op.drop_column('device_type', 'schema_id')
    # ### end Alembic commands ###
