"""add options, arguments to schema

Revision ID: 735be5d3c2b1
Revises: c246fbc0afd7
Create Date: 2025-11-25 10:52:43.532093

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735be5d3c2b1'
down_revision: Union[str, Sequence[str], None] = 'c246fbc0afd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('argument',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_argument_default_value'), 'argument', ['default_value'], unique=False)
    op.create_index(op.f('ix_argument_label'), 'argument', ['label'], unique=False)
    op.create_index(op.f('ix_argument_name'), 'argument', ['name'], unique=True)
    op.create_index(op.f('ix_argument_order'), 'argument', ['order'], unique=False)
    op.create_index(op.f('ix_argument_row'), 'argument', ['row'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_argument_row'), table_name='argument')
    op.drop_index(op.f('ix_argument_order'), table_name='argument')
    op.drop_index(op.f('ix_argument_name'), table_name='argument')
    op.drop_index(op.f('ix_argument_label'), table_name='argument')
    op.drop_index(op.f('ix_argument_default_value'), table_name='argument')
    op.drop_table('argument')
    # ### end Alembic commands ###
