"""test

Revision ID: 78c3cd5116e8
Revises: c3a3162ff19e
Create Date: 2025-10-08 08:19:19.918186

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c3cd5116e8'
down_revision: Union[str, Sequence[str], None] = 'c3a3162ff19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reserved_experiment', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reserved_experiment', 'schema_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reserved_experiment', 'schema_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reserved_experiment', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
