"""initial

Revision ID: b0a0a3429377
Revises: 
Create Date: 2026-03-01 20:26:49.001088

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b0a0a3429377'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_type',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_type_name'), 'device_type', ['name'], unique=True)
    op.create_table('server',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('websocket_port', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('production', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_api_domain'), 'server', ['api_domain'], unique=True)
    op.create_index(op.f('ix_server_ip_address'), 'server', ['ip_address'], unique=True)
    op.create_index(op.f('ix_server_name'), 'server', ['name'], unique=False)
    op.create_index(op.f('ix_server_websocket_port'), 'server', ['websocket_port'], unique=True)
    op.create_table('software',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_name'), 'software', ['name'], unique=True)
    op.create_table('device',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('maintenance_start', sa.Time(), nullable=True),
    sa.Column('maintenance_end', sa.Time(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remote_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('device_type_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'name', name='uq_device_server_name')
    )
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=False)
    op.create_table('schema',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_type', sa.Enum('control', 'ident', name='schematype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_name'), 'schema', ['name'], unique=True)
    op.create_index(op.f('ix_schema_note'), 'schema', ['note'], unique=False)
    op.create_table('argument',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_argument_default_value'), 'argument', ['default_value'], unique=False)
    op.create_index(op.f('ix_argument_label'), 'argument', ['label'], unique=False)
    op.create_index(op.f('ix_argument_name'), 'argument', ['name'], unique=True)
    op.create_index(op.f('ix_argument_order'), 'argument', ['order'], unique=False)
    op.create_index(op.f('ix_argument_row'), 'argument', ['row'], unique=False)
    op.create_table('device_software',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'software_id')
    )
    op.create_table('experiment',
    sa.Column('commands', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_remote_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('argument_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['argument_id'], ['argument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_name'), 'option', ['name'], unique=True)
    op.create_index(op.f('ix_option_output_value'), 'option', ['output_value'], unique=False)
    op.create_index(op.f('ix_option_value'), 'option', ['value'], unique=False)
    op.create_table('experiment_log',
    sa.Column('runs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_log_note'), 'experiment_log', ['note'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_log_note'), table_name='experiment_log')
    op.drop_table('experiment_log')
    op.drop_index(op.f('ix_option_value'), table_name='option')
    op.drop_index(op.f('ix_option_output_value'), table_name='option')
    op.drop_index(op.f('ix_option_name'), table_name='option')
    op.drop_table('option')
    op.drop_table('reservation')
    op.drop_table('experiment')
    op.drop_table('device_software')
    op.drop_index(op.f('ix_argument_row'), table_name='argument')
    op.drop_index(op.f('ix_argument_order'), table_name='argument')
    op.drop_index(op.f('ix_argument_name'), table_name='argument')
    op.drop_index(op.f('ix_argument_label'), table_name='argument')
    op.drop_index(op.f('ix_argument_default_value'), table_name='argument')
    op.drop_table('argument')
    op.drop_index(op.f('ix_schema_note'), table_name='schema')
    op.drop_index(op.f('ix_schema_name'), table_name='schema')
    op.drop_table('schema')
    sa.Enum('control', 'ident', name='schematype').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_software_name'), table_name='software')
    op.drop_table('software')
    op.drop_index(op.f('ix_server_websocket_port'), table_name='server')
    op.drop_index(op.f('ix_server_name'), table_name='server')
    op.drop_index(op.f('ix_server_ip_address'), table_name='server')
    op.drop_index(op.f('ix_server_api_domain'), table_name='server')
    op.drop_table('server')
    op.drop_index(op.f('ix_device_type_name'), table_name='device_type')
    op.drop_table('device_type')
    # ### end Alembic commands ###
