"""adjust schema relations

Revision ID: c246fbc0afd7
Revises: 1882e6f81d2b
Create Date: 2025-11-25 10:29:21.626411

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c246fbc0afd7'
down_revision: Union[str, Sequence[str], None] = '1882e6f81d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('device_type_schema_id_fkey'), 'device_type', type_='foreignkey')
    op.drop_column('device_type', 'schema_id')
    op.add_column('schema', sa.Column('device_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'schema', 'device_type', ['device_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schema', type_='foreignkey')
    op.drop_column('schema', 'device_type_id')
    op.add_column('device_type', sa.Column('schema_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('device_type_schema_id_fkey'), 'device_type', 'schema', ['schema_id'], ['id'])
    # ### end Alembic commands ###
