"""add userId to reservation

Revision ID: f42a893abf53
Revises: 4a9c8f4bd93d
Create Date: 2026-02-23 09:54:22.026602

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42a893abf53'
down_revision: Union[str, Sequence[str], None] = '4a9c8f4bd93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'user_id')
    # ### end Alembic commands ###
